languageCode = "en-us"
baseUrl = "https://sanderknape.com"
canonifyurls = true
title = "Sander Knape"
theme = "pixyll"
disqusShortname = "sanderknape"
paginate = 10
enableRobotsTXT = true

[indexes]
tag = "tags"

[params]
google_analytics_id = "UA-79530186-1"
paginate = true

[permalinks]
post = "/:year/:month/:filename"
